# Generated by Django 4.2.5 on 2023-10-23 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('telefono', models.CharField(max_length=15)),
                ('ubicacion', models.CharField(max_length=100)),
                ('tipo_comprador', models.CharField(choices=[('Persona', 'Persona'), ('Empresa', 'Empresa')], max_length=50)),
                ('preferencias_financiamiento', models.CharField(choices=[('Financiamiento a Plazos', 'Financiamiento a Plazos'), ('Leasing', 'Leasing'), ('Pago al Contado', 'Pago al Contado')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('telefono', models.CharField(max_length=15)),
                ('ubicacion', models.CharField(max_length=100)),
                ('financiamiento_ofrecido', models.CharField(choices=[('Financiamiento a Plazos', 'Financiamiento a Plazos'), ('Leasing', 'Leasing'), ('Pago al Contado', 'Pago al Contado')], max_length=30)),
                ('licencia_vendedor', models.CharField(max_length=50)),
                ('tipo_vendedor', models.CharField(choices=[('Persona', 'Persona'), ('Empresa', 'Empresa')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('precio_transaccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('estado_transaccion', models.CharField(max_length=20)),
                ('observaciones', models.TextField(null=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comprador')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='comprador',
            name='vehiculos_favoritos',
            field=models.ManyToManyField(related_name='compradores_favoritos', to='core.vehiculo'),
        ),
    ]
