# Generated by Django 4.2.5 on 2023-11-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comprador_vehiculos_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprador',
            name='dni',
            field=models.IntegerField(verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='dni',
            field=models.IntegerField(verbose_name='DNI'),
        ),
    ]
