# Generated by Django 4.2.5 on 2023-11-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vehiculo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='metodo_pago',
            field=models.CharField(choices=[('Financiamiento a Plazos', 'Financiamiento a Plazos'), ('Leasing', 'Leasing'), ('Pago al Contado', 'Pago al Contado'), ('Financiacion Bancaria', 'Financiacion Bancaria')], max_length=30),
        ),
    ]
